@startuml

[Client] ..> WebSockets
[Client] ..> WASM
[WebAssembly] - WASM
[Server] - WebSockets
[Server] ..> [Store]
[Server] ..> [Core]
[Server] ..> [Renderer]
[WebAssembly] ..> [Store]
[WebAssembly] ..> [Core]
[WebAssembly] ..> [Renderer]
[Store] ..> [File System]
[Store] ..> [Core]

@enduml